//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKhuyenMai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTKhuyenMai()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int Ma_CT { get; set; }
        public string Ten_CT { get; set; }
        public System.DateTime ThoiGian_BD { get; set; }
        public System.DateTime ThoiGian_KT { get; set; }
        public string mota { get; set; }
        public double PhanTramGiam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
