//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonXuat()
        {
            this.CT_DX = new HashSet<CT_DX>();
        }
    
        public int Ma_DX { get; set; }
        public System.DateTime NgayLap_DX { get; set; }
        public int Ma_KH { get; set; }
        public string Ten_KH { get; set; }
        public string DienThoai_KH { get; set; }
        public int Ma_CN { get; set; }
        public int Ma_NV_Lap { get; set; }
        public Nullable<int> Ma_CTyVC { get; set; }
        public string Ten_CtyVC { get; set; }
        public Nullable<int> Ma_The { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string TinhTrang_DX { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DX> CT_DX { get; set; }
        public virtual CtyVanChuyen CtyVanChuyen { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TheTinDung TheTinDung { get; set; }
    }
}
