//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonNhap()
        {
            this.CT_DN = new HashSet<CT_DN>();
        }
    
        public int Ma_DN { get; set; }
        public System.DateTime NgayLap_DN { get; set; }
        public int Ma_NCC { get; set; }
        public int Ma_CN { get; set; }
        public Nullable<int> Ma_NV_Nhan { get; set; }
        public string TinhTrang_DN { get; set; }
    
        public virtual ChiNhanh ChiNhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DN> CT_DN { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
