//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSLuong
    {
        public int Ma_NV { get; set; }
        public System.DateTime NgayLS { get; set; }
        public int MucLuong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
