//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChiNhanhs = new HashSet<ChiNhanh>();
            this.HoaDonNhaps = new HashSet<HoaDonNhap>();
            this.HoaDonXuats = new HashSet<HoaDonXuat>();
            this.LSLuongs = new HashSet<LSLuong>();
        }
    
        public int Ma_NV { get; set; }
        public string Ten_NV { get; set; }
        public System.DateTime NgaySinh_NV { get; set; }
        public string DienThoai_NV { get; set; }
        public string Email_NV { get; set; }
        public bool GT_NV { get; set; }
        public int DiaChi_NV { get; set; }
        public string ChucVu { get; set; }
        public int MucLuong { get; set; }
        public int SoNgayNghi { get; set; }
        public int Ma_CN { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string TrangThaiTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiNhanh> ChiNhanhs { get; set; }
        public virtual ChiNhanh ChiNhanh { get; set; }
        public virtual DiaChi DiaChi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonNhap> HoaDonNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonXuat> HoaDonXuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSLuong> LSLuongs { get; set; }
    }
}
