//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CT_DN = new HashSet<CT_DN>();
            this.CT_DX = new HashSet<CT_DX>();
            this.DanhGias = new HashSet<DanhGia>();
            this.HinhAnh_SP = new HashSet<HinhAnh_SP>();
            this.VetGiaSPs = new HashSet<VetGiaSP>();
        }
    
        public int Ma_SP { get; set; }
        public string Ten_SP { get; set; }
        public int GiaNhap { get; set; }
        public int GiaBan { get; set; }
        public System.DateTime HanDung { get; set; }
        public int NhanHieu { get; set; }
        public string Ten_NhanHieu { get; set; }
        public int Loai { get; set; }
        public string Ten_Loai { get; set; }
        public int SoLuongTon { get; set; }
        public Nullable<int> CTKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DN> CT_DN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DX> CT_DX { get; set; }
        public virtual CTKhuyenMai CTKhuyenMai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh_SP> HinhAnh_SP { get; set; }
        public virtual Loai Loai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VetGiaSP> VetGiaSPs { get; set; }
    }
}
