//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18_csdlnc19_1_da2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VetGiaSP
    {
        public int Ma_SP { get; set; }
        public System.DateTime NgayVet { get; set; }
        public int GiaNhap { get; set; }
        public int GiaBan { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
